/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.sg.producer;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class PerfTestExecutor {
	public static void main(String[] args) {
    	try {
    		ExecutorService executor = Executors.newFixedThreadPool(100);
    		
    		int numProducers = Integer.parseInt(args[0]);
    		String topic = args[1];
    		String filename = args[2];
    		
    		for (int i = 0; i < numProducers; i++) {
    			PerfTestProducer perfProducer = new PerfTestProducer(topic, filename);
    			executor.execute(perfProducer);
    		}
    		
    		executor.shutdown();
    	} catch(Exception e) {
    		e.printStackTrace();
    	}
    }
}
